tab_spaces = 2
use_field_init_shorthand = true
use_try_shorthand = true
#wrap_comments = true
max_width = 80
#format_strings = true
#imports_granularity = "Crate"
reorder_imports = true
#group_imports = "StdExternalCrate"
#wrap_comments = true
#error_on_line_overflow = true
#error_on_unformatted = true
