[package]
name = "minesweeper"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[profile.release]
panic = "abort"
strip = true

[dependencies]
rand = "0.8"
thiserror = "1"
serde = { version = "1.0", features = ["derive"] }

[dependencies.clap]
version = "3"
features = ["derive"]
